name: CI

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: averagebit.k3d

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: averagebit.k3d

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install pip dependencies
        run: pip3 install yamllint

      - name: Lint codebase.
        run: |
          yamllint .

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2204

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: averagebit.k3d

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip3 install ansible molecule[docker] docker

      - name: Test
        run: molecule test
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
          MOLECULE_DISTRO: ${{ matrix.distro }}
